import json
import asyncio
import traceback
from datetime import datetime, timedelta, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from models import models
from services.ai_service import ai_service
from google.genai import types


def _call_gemini_sync(prompt: str, json_mode: bool = False):
    """Synchronous wrapper for Gemini API call with retry."""
    config = None
    if json_mode:
        config = types.GenerateContentConfig(
            response_mime_type="application/json"
        )
    response = ai_service.client.models.generate_content(
        model='gemini-3.5-flash',
        contents=[prompt],
        config=config
    )
    return response.text


def _clean_json(text: str) -> str:
    """Clean markdown formatting from JSON responses."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()


async def generate_daily_schedule(farm_id: int, db: AsyncSession):
    """Generate daily schedule using a rule-based approach + AI formatting.
    
    This ensures tasks are strictly based on SOPs, crop cycles, and real events,
    while AI is only used to organize and present them nicely.
    """
    try:
        today_date = datetime.utcnow().date()
        current_month = today_date.month
        current_weekday = today_date.weekday() # 0 = Mon, 6 = Sun
        
        raw_tasks = []
        
        # 1. Fetch SOPs (RecurringTasks)
        # In a real app we'd parse cron expression. For now, we'll just fetch active ones
        # and assume they are daily, or if we had a proper cron parser we'd check it.
        # As a simplification for this MVP, we include all active recurring tasks.
        sops_res = await db.execute(select(models.RecurringTask).where(
            models.RecurringTask.farm_id == farm_id,
            models.RecurringTask.is_active == True
        ))
        for sop in sops_res.scalars().all():
            zone_info = f", Zone ID: {sop.zone_id}" if sop.zone_id else ""
            raw_tasks.append(f"[SOP日常任务] {sop.title} - {sop.description}{zone_info}")

        # 2. Fetch Fertilizer Schedules for current month
        fert_res = await db.execute(select(models.FertilizerSchedule).where(
            models.FertilizerSchedule.farm_id == farm_id,
            models.FertilizerSchedule.month == current_month
        ))
        for fert in fert_res.scalars().all():
            raw_tasks.append(f"[本月施肥排程] 施放 {fert.fertilizer_name}, 数量: {fert.quantity} {fert.unit} (请安排在此月内完成)")

        # 3. Fetch ZoneCropPlans
        crop_res = await db.execute(select(models.ZoneCropPlan).where(
            models.ZoneCropPlan.farm_id == farm_id
        ))
        for plan in crop_res.scalars().all():
            zone_info = f"Zone ID: {plan.zone_id}"
            if plan.status == "growing" and plan.expected_harvest_date:
                days_left = (plan.expected_harvest_date - today_date).days
                if days_left <= 3 and days_left > 0:
                    raw_tasks.append(f"[采收预警] {plan.crop_name} 还有 {days_left} 天采收, 准备采收工具 ({zone_info})")
                elif days_left <= 0:
                    raw_tasks.append(f"[今日采收] {plan.crop_name} 已经可以采收! ({zone_info})")
            elif plan.status == "harvesting" and plan.harvest_end_date:
                days_over = (today_date - plan.harvest_end_date).days
                if days_over >= 0:
                    raw_tasks.append(f"[采收结束] {plan.crop_name} 采收期已结束, 请清理残株并准备翻土 ({zone_info})")
            elif plan.status == "preparing":
                next_crop = f" (准备种: {plan.next_crop_name})" if plan.next_crop_name else ""
                raw_tasks.append(f"[翻土准备] 执行翻土、施底肥、消毒作业{next_crop} ({zone_info})")

        # 4. Fetch Inventory Alerts
        inv_res = await db.execute(select(models.InventoryItem).where(
            models.InventoryItem.farm_id == farm_id
        ))
        for item in inv_res.scalars().all():
            # Simplistic threshold logic (e.g., < 100 for baskets, < 5 for chemicals)
            if item.quantity < 50: 
                raw_tasks.append(f"[库存警告] {item.name} 库存偏低 ({item.quantity} {item.unit}), 请尽快盘点或采购")

        # 5. Fetch Photo Issues
        yesterday = datetime.utcnow() - timedelta(days=1)
        res = await db.execute(select(models.Photo).where(
            models.Photo.farm_id == farm_id,
            models.Photo.captured_at >= yesterday,
            models.Photo.health_status.in_(["warning", "critical"])
        ))
        for p in res.scalars().all():
            zone_info = f"Zone ID: {p.zone_id}" if p.zone_id else "未知区域"
            raw_tasks.append(f"[异常处理] {zone_info} 发现异常: {p.ai_analysis}")

        print(f"[AI Scheduler] Farm {farm_id}: Gathered {len(raw_tasks)} rule-based tasks")

        # If no tasks generated by rules, fallback to a general task
        if not raw_tasks:
            raw_tasks.append("[日常巡检] 全区巡视，检查是否有虫害或缺水状况")

        # Format prompt for AI Organizer
        tasks_text = "\n".join(f"- {t}" for t in raw_tasks)
        
        prompt3 = f"""【农场管家 AI 整理员】
你是一个帮助农场老板整理每日行程的得力助手。
我已经透过后台规则产生了一份「必须执行的任务清单」。你的工作是把这些粗糙的文字，整理成干净、专业、适合派发给工人的 JSON 格式任务表。

### 规则生成的原始任务清单：
{tasks_text}

### 你的工作要求：
1. 归纳与合并：如果有多条类似的巡检或盘点任务，可以合理合并成一个。
2. 翻译与润饰：把任务标题和描述写成易懂的语言，语气专业。
3. 提取 Zone ID：如果原始任务里有提到 `Zone ID: X`，请务必把它提取出来填入 JSON 的 `zone_id` 栏位。如果没有提到，填 `null`。
4. 你**绝对不可**自己发明这里没有提到的新任务（例如不要自己加什么土壤检测，除非原始清单有）。
5. 限制数量：如果任务太多，挑选最重要、最紧急的 5-8 个即可（尤其是带有 [采收预警]、[今日采收]、[异常处理] 的绝对优先）。

请输出一个 JSON 阵列（Array），包含今天要执行的任务列表。
每个任务必须是一个 JSON 对象，包含以下栏位：
- "title": 任务标题（简短、清晰）
- "zone_id": 提取到的区域ID（整数或 null）
- "description": 任务详细说明（30字以内，告诉工人要做什么）

只回传纯 JSON 阵列，不要包含其他文字或 markdown 标签。"""

        print("[AI Scheduler] Calling AI Organizer...")
        coordinator_response = await asyncio.to_thread(_call_gemini_sync, prompt3, True)
        
        tasks_json = _clean_json(coordinator_response)
        
        # Validate JSON before saving
        parsed = json.loads(tasks_json)
        if not isinstance(parsed, list):
            # If it returned an object with a key, try to extract the array
            if isinstance(parsed, dict):
                for key in parsed:
                    if isinstance(parsed[key], list):
                        parsed = parsed[key]
                        tasks_json = json.dumps(parsed, ensure_ascii=False)
                        break
            else:
                raise ValueError(f"Expected JSON array, got {type(parsed)}")
        
        print(f"[AI Scheduler] Parsed {len(parsed)} tasks successfully")

        today_str = datetime.utcnow().strftime("%Y-%m-%d")
        
        # Save to ProposedSchedule
        exist_res = await db.execute(select(models.ProposedSchedule).where(
            models.ProposedSchedule.farm_id == farm_id,
            models.ProposedSchedule.date == today_str
        ))
        existing = exist_res.scalar_one_or_none()
        
        if existing:
            existing.tasks_json = tasks_json
            existing.status = "draft"
        else:
            new_schedule = models.ProposedSchedule(
                farm_id=farm_id,
                date=today_str,
                tasks_json=tasks_json,
                status="draft"
            )
            db.add(new_schedule)
        
        await db.commit()
        print(f"[AI Scheduler] Schedule saved for farm {farm_id}, date {today_str}")
        return parsed
        
    except Exception as e:
        print(f"[AI Scheduler ERROR] {e}")
        traceback.print_exc()
        raise
