import { api } from '../api.js';
import { t } from '../i18n.js';
import { auth } from '../auth.js';

export async function renderDailySummary(container) {
  const user = auth.getUser();
  
  container.innerHTML = `
    <div class="page-container">
      <div class="glass-panel" style="text-align: center; padding: 3rem;">
        <div class="spinner"></div>
      </div>
    </div>
  `;

  try {
    const params = {};
    if (user.farmId) params.farm_id = user.farmId;
    else {
      const globalFarmSelect = document.getElementById('global-farm-select');
      if (globalFarmSelect && globalFarmSelect.value !== 'all') {
        params.farm_id = parseInt(globalFarmSelect.value);
      }
    }

    const reports = await api.reports.daily(params);
    const farms = await api.farms.list();
    const farmMap = {};
    farms.forEach(f => farmMap[f.id] = f.name);

    container.innerHTML = `
      <div class="page-container" style="animation: fadeIn 0.4s ease-out;">
        <div class="summary-header glass-panel">
          <div>
            <h2 style="margin: 0 0 0.5rem 0; color: var(--primary-dark);">AI Daily Insights</h2>
            <p class="text-secondary" style="margin: 0;">Get an overview of your farms' status generated by FarmWatch AI.</p>
          </div>
          <div class="ai-icon">✨</div>
        </div>

        <div class="reports-grid">
          ${reports.length ? reports.map((r, i) => `
            <div class="report-card glass-panel fade-in" style="animation-delay: ${i * 0.1}s">
              <div class="report-header">
                <h3 class="report-farm">${farmMap[r.farm_id] || 'Farm ' + r.farm_id}</h3>
                <span class="report-date">${r.date}</span>
              </div>
              <div class="report-body">
                <p>${r.summary}</p>
              </div>
              <div class="report-footer text-secondary">
                Generated at ${new Date(r.generated_at).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
              </div>
            </div>
          `).join('') : '<div class="glass-panel"><p class="text-secondary text-center">No reports available for today.</p></div>'}
        </div>
      </div>

      <style>
        .summary-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
          padding: 2rem;
          background: linear-gradient(135deg, rgba(255,255,255,0.8), rgba(255,255,255,0.4));
        }
        .ai-icon {
          font-size: 3rem;
          animation: float 3s ease-in-out infinite;
        }
        
        .reports-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
          gap: 1.5rem;
        }
        
        .report-card {
          padding: 1.5rem;
          border-left: 4px solid var(--primary);
          transition: transform 0.3s ease, box-shadow 0.3s ease;
          display: flex;
          flex-direction: column;
        }
        .report-card:hover {
          transform: translateY(-5px);
          box-shadow: 0 10px 20px rgba(0,0,0,0.05);
        }
        
        .report-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
          border-bottom: 1px solid var(--border-color);
          padding-bottom: 0.5rem;
        }
        .report-farm {
          margin: 0;
          color: var(--primary-dark);
          font-family: 'Outfit', sans-serif;
          font-size: 1.25rem;
        }
        .report-date {
          font-size: 0.9rem;
          color: var(--text-secondary);
          background: var(--bg-color);
          padding: 0.2rem 0.6rem;
          border-radius: 12px;
        }
        
        .report-body {
          flex: 1;
          color: var(--text-primary);
          line-height: 1.6;
          margin-bottom: 1rem;
        }
        
        .report-footer {
          font-size: 0.8rem;
          text-align: right;
          border-top: 1px dashed var(--border-color);
          padding-top: 0.5rem;
        }
        
        @keyframes float {
          0% { transform: translateY(0px); }
          50% { transform: translateY(-10px); }
          100% { transform: translateY(0px); }
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .fade-in {
          animation: fadeIn 0.5s ease-out backwards;
        }
      </style>
    `;
  } catch (err) {
    console.error('Failed to load summary:', err);
    container.innerHTML = `<div class="page-container"><p style="color:var(--danger)">Error loading daily summary.</p></div>`;
  }
}
